image: docker:latest
stages:
  - build
services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  CI_REGISTRY_IMAGE: registry.gitlab.com/hgalytoby/vue-flask-uwsgi-gunicorn-nginx-docker-gitlab-heroku
  HEROKU_REGISTRY: registry.heroku.com/vue-python-nginx-gitlab-docker/web

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build_and_deploy_to_heroku:
  stage: build
  services:
    - docker:dind
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
    - docker tag $CI_REGISTRY_IMAGE:latest $HEROKU_REGISTRY:latest
    - docker push $HEROKU_REGISTRY:latest
    - docker run --rm -e HEROKU_API_KEY=$HEROKU_API_KEY dickeyxxx/heroku-cli heroku container:release web --app vue-python-nginx-gitlab-docker